spring:
server:
  port: 9090
springdoc:
  packagesToScan: com.formacion.controller
  pathsToMatch: /**
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.133:8761/eureka
    register-with-eureka: true
