spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.133:3309/academia?serverTimezone=UTC
    username: root
    password: abc123.
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
springdoc:
  packagesToScan: com.curso.controller
  pathsToMatch: /**
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.133:8761/eureka
    register-with-eureka: true
